### ISSUE TITLE
API: missing stats and Vocchain information

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#11]
The actual landing page has more information that the one given by [/chain/info](https://developer.vocdoni.io/vocdoni-api/info). Not sure if divide into two endpoint (like chain/info and chain/stats) or use the same. Here a list of stats showed on the explorer that are not returned on the current call:

- [x] Validators numbers
- [x] Sync status
- [x] Genesis block date
- [x] Total Processes
- [x] Total Orgs
- [x] Total Votes

Here the old implementation https://docs.vocdoni.io/architecture/services/gateway.html#get-stats

Once implemented we should update:

- [ ] SDK
- [x] Developer portal

**Comment by selankon** [comment]
Added two tasks to update the SDK and the developer portal with the new info once deployed

**Comment by selankon** [comment]
Hi! @jordipainan  I tried to get the info but it seems that there are no parameter called Organizations count. Is this expected?

```
➜ curl https://api-dev.vocdoni.net/v2/chain/info -s | jq
{
  "chainId": "vocdoni-development-77",
  "blockTime": [
    10000,
    11538,
    11501,
    11489,
    11495
  ],
  "electionCount": 61,
  "genesisTime": "2023-02-14T18:33:52.180295926Z",
  "height": 11541,
  "syncing": false,
  "blockTimestamp": 1676538064,
  "transactionCount": 1239,
  "validatorCount": 4,
  "voteCount": 757
}
```

**Comment by jordipainan** [comment]
```golang
type ChainInfo struct {
	ID                      string    `json:"chainId"`
	BlockTime               [5]int32  `json:"blockTime"`
	ElectionCount           uint64    `json:"electionCount"`
	GenesisTime             time.Time `json:"genesisTime"`
	Height                  uint32    `json:"height"`
	Syncing                 bool      `json:"syncing"`
	Timestamp               int64     `json:"blockTimestamp"`
	TransactionCount        uint64    `json:"transactionCount"`
	ValidatorCount          uint32    `json:"validatorCount"`
	VoteCount               uint64    `json:"voteCount"`
	CircuitConfigurationTag string    `json:"cicuitConfigurationTag,omitempty"`
}```

I missed the organizationCounter will add it asap

**Comment by selankon** [comment]
Prepared to be merged into developer portal here: 

https://github.com/vocdoni/developer-portal/pull/38

Awaiting organizationsCount

**Comment by selankon** [comment]
I reopened the issue because this is not implemented on the SDK yet

**Comment by jordipainan** [comment]
All done from my side :)

**Comment by selankon** [comment]
https://github.com/vocdoni/vocdoni-sdk/pull/104/files

This adds this attributes to the SDK

**Comment by p4u** [comment]
VoteCount seems to be reported wrong. It must be checked and tests must be added to assure it works as expected.

**Comment by selankon** [comment]
I guess we should close this and open an issue on vocdoni node or wherever
