### ISSUE TITLE
Merge Repos (vocdoniapp <> onvote)

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#115]
We want to improve our codebase and make it easier to deploy new changes, by unifying the 2 repos in one, creating vars and themes to do it. 

- [x] Split the CSS into different themes
- [x] Test the different themes
- [x] Test the deploy
- [x] Remove branch
- [x] Unify into a single branch

**Comment by elboletaire** [comment]
Done, and already deployed everywhere using the same repo and themes:

https://dev.onvote.app
https://stg.onvote.app
https://onvote.app

https://app-dev.vocdoni.io
https://app-stg.vocdoni.io
https://app.vocdoni.io
