### ISSUE TITLE
[ Bugs ] Change settings

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#122]
- [x] Submit the "Change settings" proposal is not possible, due a "Estimation gas error":

` Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction=`

![Image](https://github.com/vocdoni/interoperability/assets/6894329/ec7e0676-f6a7-4d74-afdc-743b0a877d44)

- [x] The string: `Minimum approval     1 2 of {{total}} authorized addresses` is not rendered well.

- [x] The "Reset changes" button doesn't work with "Add wallets" & "Remove wallets" (the is no changes)

**Comment by selankon** [comment]
This tasks are fixed on the following commits:

```
* bcf828fe - (43 seconds ago) Delete unused function - selankon
* 28be13ca - (56 seconds ago) Fix new committee final count - selankon
* 898d7ec5 - (30 minutes ago) Fix reset all - selankon
* 576332da - (41 minutes ago) Filter non empty actions - selankon
* dc5a1579 - (81 minutes ago) Prevent undefined actions - selankon
* 11fbab86 - (2 hours ago) Fix label - selankon
```
