### ISSUE TITLE
New Census3 API spec to support rounded census accuracy

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/interoperability#123]
The API spec of Census3 will change after https://github.com/vocdoni/census3/pull/135/. 

Main changes:
 * `/strategies/{strategyID}/estimation` endpoint now accept a new URL query parameter `anonymous` (`false` by default) to estimate the census resulting of the desired strategy including the census accuracy (`100.0` by default). 
 Ex: `/strategy/12/estimation?anonymous=true`
 * `/censuses/{censusID}` & `/censuses/strategy/{strategyID}` endpoints include the census accuracy stored in the database.

Checkout the API spec updated [here](https://github.com/vocdoni/census3/blob/7e9f9c8e10c84b5d4606182d8ca2fe38d185d792/api/README.md).

**Comment by marcvelmer** [comment]
Done in the SDK: https://github.com/vocdoni/vocdoni-sdk/pull/332
