### ISSUE TITLE
Import blog posts from Aragon blog to the new Vocdoni blog

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/interoperability#126]
- [x] Request the export file to the responsible for the Aragon blog @jpaulet 
- [x] Curate and list the posts that should be imported to the new blog
- [x] Import the archive on the new Vocdoni blog

**Comment by jpaulet** [comment]
The blog from Aragon is created manually and they told me is not possible to "export", but they can send us the assets.

**Comment by ferranrego** [comment]
No problem @jpaulet, I already imported them. thanks!
