### ISSUE TITLE
Results for Multiquestion

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#135]
Adapt the results to show the correct % when voting with multi-choice (with abstain).

- [x] Adapt the results to make it work in a generic way (reading the metadata of the election, counting the nº of abstains, etc.)
- [x] Checks & tests
- [x] Solve bug in "general" results (single-choice)

**Comment by elboletaire** [comment]
Not closing it for further testing, but everything seems ok now (and already deployed in all environments).
