### ISSUE TITLE
SDK Support for Anonymous voting 

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/interoperability#14]
The current supported flow for anonymous voting is as follows:
1. The administrator creates a census for the election.
2. Each participant creates their ZkAddress and submits it to the administrator to be added to the census.
3. The administrator publishes the election with the created census and share the electionID with the participants.
4. Each participant creates a proof that he or she is already registered in the census election in order to be able to vote. 

To support these steps, some endpoints have been created:
* `/census/{censusRoot}/type`: returns the type of the census provided (by its censusRoot). It allows to check the census type to generate the correct census proof before performing a vote.
* `/chain/info/circuit`: returns the configuration data of the circuit that is currently used on the Vochain. This information includes the correct URI's to download the circuit artifacts to use the circuit in the SDK. These artifacts will be downloaded.

I'm sure more endpoints will be needed to support the full functionality.

I'm also working on a sample code of a possible implementation of the ZkAddress in TypeScript, and some other functions to generate the circuit inputs as needed: https://gist.github.com/lucasmenendez/d4a3d5c9e107a04449a04caee34e2f8b

- [ ] add to api (if it is needed)
- [ ] add to documentation
- [x] add to SDK

**Comment by lucasmenendez** [comment]
After the implementation of the zkweighted census the zkindexed will no longer be used and the documentation will be updated to also include this change.

The deprecation of indexed census is already merged on [vocdoni-node@master](https://github.com/vocdoni/vocdoni-node/commit/f10cef8fb3204d73ce2251eff239d045933d813c).

**Comment by jpaulet** [comment]
Blocked by: https://github.com/vocdoni/interoperability/issues/66
