### ISSUE TITLE
Share options in the voting page

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#148]
As voter I want to have a easy way to share the voting process to others.

Add a new "Share" button in the public voting page, that allows the voter to: 

- [x] Add a share button (top-right area, in the same row of "Schedule" but floating in the right):
![image](https://github.com/vocdoni/interoperability/assets/6894329/05e0b9aa-0e6a-42c8-a1b9-ff7bfe1c05ff)

When clicked, a modal appear: 
![image](https://github.com/vocdoni/interoperability/assets/6894329/cef739c4-5dfd-43f1-bb25-6f487c4e09f8)

With the following share options: 
- [x]  Share with Telegram
- [x]  Share with Whatsapp
- [x]  Share on Twitter
- [x] Share on Facebook
- [x]  Share via Mail
- [x] Copy URL component

Make sure to share ONLY the URL part without the # if present (to prevent sharing the PK if we use the auth with PK in the URL).

**Comment by selankon** [comment]
We can use  https://www.npmjs.com/package/react-share

**Comment by selankon** [comment]
It actually exists a "share" component when voted, we should just adapt this

![image](https://github.com/vocdoni/interoperability/assets/16777076/33a2a982-07bd-4975-870d-f106027b91e5)
