### ISSUE TITLE
API: Election info endpoint doesn't return organiztion Id

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#15]
```
➜ curl https://api-dev.vocdoni.net/v2/elections/c5d2460186f7f1125b3ad1e0f558c017898d7753e93f58cb503d020000000004 -s | jq
```

Should have the organizationId somewhere

- [x] Fix API response
- [x] Add to the SDK 
- [x] Add to developer portal

**Comment by selankon** [comment]
Also another thing that is not returned by elections info endpoint is the start block and end block, instead it return the dates. I don't know if could be useful to return start/end block height also.

**Comment by p4u** [comment]
We used to return the start and end block, but when designing the API we wanted to abstract the user from this... so we switched to dates. I don't know, if there is utility we can return it. @jpaulet ?

**Comment by jpaulet** [comment]
I think that it's a good practice to abstract it and return the date
instead. I can't think in any use case that the block is used (only to
review it in a block scan), even for the more expert users...

But this is only true if the block<>date conversion is quite accurate and
no significant delays occur. Otherwise, I do find it interesting to be able
to consult the start/end specific block (perhaps another endpoint) even if
it is for internal use, for example, if a vote must end at 10:00 and it has
not finished, then we can check if it's because the block mining has not
yet been reached or if there is some other problem.

Missatge de Pau ***@***.***> del dia dj., 16 de febr. 2023 a
les 20:50:

**Comment by selankon** [comment]
@p4u at this moment `organizationId` is empty:

```
curl https://api-dev.vocdoni.net/v2/elections/c5d2460186f70f6f0e8084fd8b281b40bfaf43e13a602cde8f2e02000000000a -s | jq .
{
  "electionId": "c5d2460186f70f6f0e8084fd8b281b40bfaf43e13a602cde8f2e02000000000a",
  "organizationId": "",
```

**Comment by p4u** [comment]
Should be fixed now

**Comment by selankon** [comment]
I confirm is working: 

```
curl https://api-dev.vocdoni.net/v2/elections/c5d2460186f7f1125b3ad1e0f558c017898d7753e93f58cb503d020000000002 -s | jq .
```

**Comment by selankon** [comment]
But not for:

```
curl -L -X GET 'https://api-dev.vocdoni.net/v2/accounts/0x2e5b02237f4489d53a7fe4ae2134fabef8323507/elections/page/0' -s | jq

{
  "elections": [
    {
      "electionId": "c5d2460186f72e5b02237f4489d53a7fe4ae2134fabef8323507020400000000",
      "organizationId": "",
      "status": "canceled",
      "startDate": "2023-03-02T09:58:40Z",
      "endDate": "2023-04-06T19:54:36.844784608Z",
      "voteCount": 0,
      "finalResults": true
    },
```

But working  for:

```
➜ curl -L -X GET 'https://api-dev.vocdoni.net/v2/elections/page/0' -s | jq
{
  "elections": [
    {
      "electionId": "c5d2460186f7cb0081afeae4073c0f75a4b134cdc67c8995e022020000000000",
      "organizationId": "cb0081afeae4073c0f75a4b134cdc67c8995e022",
      "status": "RESULTS",
      "startDate": "2023-03-01T23:37:22.314064992Z",
      "endDate": "2023-03-02T00:02:36.841172825Z",
      "voteCount": 100,
      "finalResults": true
 ```

**Comment by p4u** [comment]
I'm not sure `accounts/:accountID/elections/page/:page` needs to return the organizationID since it is the accountID, which is already known by the caller. But I added anyway, so it should be fixed.

**Comment by selankon** [comment]
https://github.com/vocdoni/developer-portal/pull/43 

documented

**Comment by selankon** [comment]
& done also on the SDK side:

https://github.com/vocdoni/vocdoni-sdk/pull/103
