### ISSUE TITLE
API: return 204 (No content)

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#16]
See the PR https://github.com/vocdoni/vocdoni-node/pull/820

List of endpoints returning 204:
- /chain/transactions/reference/:hash
- /chain/transactions/reference/index/:globalIndex
- /chain/transactions/:height/:index

List of endpoints returning 404:
- /votes/verify/:electionId/:voteId
- /votes/:voteId
- /elections/:electionId
- /elections/:electionId/keys
- /elections/:electionId/votes
- /elections/:electionId/scrutiny

Tasks:
- [x] documented
- [x] sdk

**Comment by p4u** [comment]
@marcvelmer this is gonna be in DEV as soon as you confirm the changes

**Comment by selankon** [comment]
Documented on https://github.com/vocdoni/developer-portal/pull/37

**Comment by selankon** [comment]
This is done also on the sdk so I close it
