### ISSUE TITLE
Flow faucet error

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#162]
1. A la faucet podem fer q es permeti donar fins a 2 o 3 cops a la mateixa address la quantitat inicial de 5 tokens per crear l'account
2. El flow de la UI s'ha d'adaptar, si ja has aconseguit un Faucet PKG, reutilitzar-lo i no demanar un de nou
3. També al flow de la UI, comprovar abans d'anar a la faucet si tens suficients tokens per tirar la TX de Register SIK, si en tens no passar per la faucet

**Comment by emmdim** [comment]
Relevant flow: https://github.com/vocdoni/ui-scaffold/blob/develop/src/components/Account/Create.tsx#L158

**Comment by emmdim** [comment]
@elboletaire  added an initial addaptation of including the faucet pacakge in account creation.
I am trying to understand what exactly uis the expected behaviour after this first step
