### ISSUE TITLE
Gitcoin Passport

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#163]
- [x] https://github.com/vocdoni/ui-scaffold/issues/605

**Comment by emmdim** [comment]
* [ ]  Rounding issue: https://github.com/vocdoni/census3/issues/176
* [ ] When there is only one stamp chosen the produced predicate is ` GPS AND:mul (GPS:Stamp OR GPS:Stamp)` @lucasmenendez  not sure if this is correct or not!
* []  When removing GPS weight the votes still have the weight of the GTC scrore: https://github.com/vocdoni/census3/issues/177

**Comment by lucasmenendez** [comment]
Regarding the question about the predicate, yes it is correct, but we have a bug in the lexer. Right now it does not support same symbol in both sides of a level. It will support it ASAP.

Regarding the third topic, I does not understand the issue, there are two scores about Gitcoint, the Gitcoin Passport Score and the Gitcoin Stamps score. Are you talking about that?
