### ISSUE TITLE
Move the "max census expected" component to the preview page

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#168]
As Vocdoni, we want to improve the way the processes are created and make more obvious the relation between the `max census participation` and the election price in tokens. For that reason and to make easier to understand for the organizers, we should move the slider component from the `Step 3: Census` to the `Step 4: Preview`.

ToDo:
- [ ] Move the component to the next page (preview) as indicated in the design.
- [ ] Move the `Maximum participation expected: X% (Y eligible voters)` just below the slider component.
- [ ] Relate the slider with the token cost and recalculate when the organizer change it and press the "Recalculate" button.
- [ ] Add a "Recalculating cost" loader in the "cost" component.
- [ ] Improve the text: `You have a pool of 26,211 FORTH potential voters.` to `You have a pool of 26,211 potential FORTH voters.`

Preview page visual improvements:
- [ ] Change the first column of the preview info from 30% to 25%. 
- [ ] Add the border in the "Cost" and "Accept terms" components
- [ ] Remove the "SET UP YOUR VOTING PROCESS" title on the preview component
- [ ] Change the "You don't have enough tokens to create this process." color text from black to red.
- [ ] Increase the padding of the "Preview" component to 30px.

We should move this component from the "Census" step to to the "Preview" step, and by default show it hidden, only if the user selects it specifically, we will show it and let him change it.

From here: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/ba20984c-7c9e-4036-ab32-268b27c6f5b9)

To:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e4970b3d-d29e-44fb-aa3d-ee393ac56d1d)

And the **final design** on the preview page:
![preview](https://github.com/vocdoni/interoperability/assets/6894329/e001eb23-8bd0-4683-a6b1-8ecd58ef655b)

Reference: https://github.com/vocdoni/ui-scaffold/issues/479

**Comment by emmdim** [comment]
ping @gerouvi please let me know on the update of this issue Is it started?
