### ISSUE TITLE
Plugin Status Review (09/05)

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#184]
- [x] Members count in the Dashboard & Members pages takes very long to appear and no cache seems to be used, as every time it takes more than 20 sec.. On top of that, it shows "0" but you see X members in the list :

![Image](https://github.com/vocdoni/interoperability/assets/6894329/e7ec3932-4005-43f8-bb67-8be8d87d2ac8)
![Image](https://github.com/vocdoni/interoperability/assets/6894329/695b30c0-04e7-4a64-8667-07cabc1b20a2)
![Image](https://github.com/vocdoni/interoperability/assets/6894329/0a2ab745-d73c-4218-ae8b-7a1b2f6f03f4)

URL: https://ipfs.eth.aragon.network/ipfs/QmQzDvUUJkUcNxbUyscYaV7N9PzBVLtvqUCkjpNdEQ1Cm3/#/daos/sepolia/0x77737ac1c365ed1204a78300a4046245ddece6cf/dashboard

Extra: Also, while scanning the token (+10 min), it shows "0". Can we add a "Scanning..." text after the "Token-based" if we detect that the token is still being scanned?.

- [x]  In the "Members page", the "See All Holders" button, shows the "Mint tokens" page

- [x] Mint page error (when the token is not yet scanned): 

GET https://census3-aragon.vocdoni.net/api/strategies/20/holders?pageSize=-1 [HTTP/2 404  387ms] Error: no token holders found

and once is scanned:

https://census3-aragon.vocdoni.net/api/strategies/undefined/holders?pageSize=-1 [HTTP/2 400  471ms] Error: malformed strategy ID, it must be an integer: strconv.Atoi: parsing "undefined": invalid syntax

- [x]  After voting, the "select option" component, didn't disappear:

![Image](https://github.com/vocdoni/interoperability/assets/6894329/b072f6f3-1b9c-4648-8331-b66f7a56f7f6)

**Comment by selankon** [comment]
> Extra: Also, while scanning the token (+10 min), it shows "0". Can we add a "Scanning..." text after the "Token-based" if we detect that the token is still being scanned?.

This won't be needed when merged this from Notion issues:

> 2) Add a census3 scan check (in addition to subgraph check) to DAO pending screen to not allow user to advance until initial scan has completed.

This will show a (we are building your DAO) message until the scan is finished

**Comment by selankon** [comment]
>  Mint page error (when the token is not yet scanned):

Same as commented before. In Addition I did a fix to prevent the error you said
