### ISSUE TITLE
allow passing optional `delta` param to `/elections/id` endpoint

### ISSUE THREAD

**Issue by altergui** [vocdoni/interoperability#187]
```
curl -L -X POST 'https://api-dev.vocdoni.net/v2/elections/id' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-raw '{
  "censusOrigin": 2,
  "envelopeType": {
    "anonymous": true,
    "costFromWeight": true,
    "encryptedVotes": true,
    "serial": true,
    "uniqueValues": true
  },
  "organizationId": "4311334261b6135bf07fa2afb2e1ec6f9ba836be"            
}'
```
```
{"electionID":"ab7cc99cda4c4311334261b6135bf07fa2afb2e1ec6f9ba836be021f00000001"}
```

now this endpoint supports passing a `delta` parameter, which if not passed, the default (0) means returning NEXT electionID (to not break backwards compatibility). 

```
curl -L -X POST 'https://api-dev.vocdoni.net/v2/elections/id' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-raw '{
  "censusOrigin": 2,
  "envelopeType": {
    "anonymous": true,
    "costFromWeight": true,
    "encryptedVotes": true,
    "serial": true,
    "uniqueValues": true
  },
  "organizationId": "4311334261b6135bf07fa2afb2e1ec6f9ba836be", 
  "delta": 0
}'
```
```
{"electionID":"ab7cc99cda4c4311334261b6135bf07fa2afb2e1ec6f9ba836be021f00000001"}
```

to return last election created, pass delta=-1

```
curl -L -X POST 'https://api-dev.vocdoni.net/v2/elections/id' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-raw '{
  "censusOrigin": 2,
  "envelopeType": {
    "anonymous": true,
    "costFromWeight": true,
    "encryptedVotes": true,
    "serial": true,
    "uniqueValues": true
  },
  "organizationId": "4311334261b6135bf07fa2afb2e1ec6f9ba836be",
  "delta": -1
}'
```
```
{"electionID":"ab7cc99cda4c4311334261b6135bf07fa2afb2e1ec6f9ba836be021f00000000"}
```

or for the N election in the future, pass delta=N-1 

```
curl -L -X POST 'https://api-dev.vocdoni.net/v2/elections/id' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-raw '{
  "censusOrigin": 2,
  "envelopeType": {
    "anonymous": true,
    "costFromWeight": true,
    "encryptedVotes": true,
    "serial": true,
    "uniqueValues": true
  },
  "organizationId": "4311334261b6135bf07fa2afb2e1ec6f9ba836be",
  "delta": 3
}'
```
```
{"electionID":"ab7cc99cda4c4311334261b6135bf07fa2afb2e1ec6f9ba836be021f00000004"}
```

**Comment by marcvelmer** [comment]
I still don't understand why this method needs so many data in the POST request if the next election identifier doesn't depend from that, no matter which values we use. @altergui @p4u

**Comment by altergui** [comment]
the next election identifier does depend on all of the passed data. it is used to construct the electionID. but it changes only a couple bytes, so it's easy to miss.

```

// processID = chainID[6bytes] + organizationAddress[20bytes] + proofType[1byte] + envelopeType[1byte] + nonce[4bytes]
```

proofType is a synonym for censusOrigin in this case

so changing any of the envelopeType bools, will only modify a single byte.

for example

```
6b342d99f21861ad9b21167a350ceb045d5f9e9a2a5f8cddc7f3011f00000005
6b342d99f21861ad9b21167a350ceb045d5f9e9a2a5f8cddc7f3010f00000005
                            encryptedVotes=true ------^
```

**Comment by altergui** [comment]
FWIW, the new `delta` parameter is optional. you can omit it and it will default to 0, keeping backwards compatibility

**Comment by marcvelmer** [comment]
Ok, but shouldn't be the organization address + election count + chain identifier be enough for creating an election identifier which cannot have collisions? Just asking

**Comment by p4u** [comment]
Here the discussion https://github.com/vocdoni/protocol/discussions/28

We decided to add "envelopeType" to let the CSP or other external players to know the type of election. So they can use the processID to identify (for example) if the process is anonymous, then either use blind signature or plain (in case of CSP).

**Comment by marcvelmer** [comment]
Done in the SDK

**Comment by altergui** [comment]
PR was merged a while back but we forgot to close this issue, closing now
