### ISSUE TITLE
feature: improve and unify pagination and filtered pagination

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#188]
**Describe the feature**
Improve and unify all endpoints with pagination.

**Motivation**
Current pagination implementation has some issues and limitations.

**Proposal**
To have, preferably via query params, a way to filter all paginated results by indexed fields. 

Current filtering implementation has a specific POST endpoint for filtering results... that's one of the things that could be improved by just using GET params on its original endpoint.

For example, [list elections filtered](https://developer.vocdoni.io/vocdoni-api/list-elections-filtered) should not exist and, instead, [list elections](https://developer.vocdoni.io/vocdoni-api/list-elections) should implement the filtering via query params.

Taking that as an example:
- `/elections` should be the only URL to get the elections filtered and paginated
- Any indexed field should be a possible GET param to filter, i.e. `?finalResults=true&manuallyEnded=true`
- `limit` and `page` may be reserved words for pagination purposes. `order` too, but that's a bit more complicated since you need to specify the direction (asc/desc).
- the results should return, among the current `processes` key, other keys with information like the total results with the applied filter

Example request with pagination and filtering:

~~~
https://api-dev.vocdoni.net/v3/elections?page=1&limit=20&finalResults=true
~~~
> note the v3 in the url... I'm aware these breaking changes may require defining a new version.

Expected response:

~~~js
{
  "elections": [
    // a maximum of 20 elections with finalResults
    {
      // election body
    },
   "total": 140 // the total number of filtered results
}
~~~

Other information like the page or the limit could also be added to this response but, considering is info given by the requester... I don't see it as a requirement. The important one here is `total`.

**Affected routes**

## Elections
- [x] `GET /elections` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] organizationId: string;
  - [x] electionId: string;
  - [x] withResults: boolean;
  - [x] finalResults: boolean;
  - [x] manuallyEnded: boolean;
  - [x] status: Exclude<AllElectionStatus, ElectionStatus.ONGOING | ElectionStatus.UPCOMING>;

and this new endpoint replaces all the following, marked deprecated:
- [x] `GET /elections/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-elections))
- [x] `GET /accounts/{organizationID}/elections/page/{page}` ([docs](https://developer.vocdoni.io/vocdoni-api/list-organization-elections))
- [x] `GET /accounts/{organizationID}/elections/status/{status}/page/{page}` ([docs](https://developer.vocdoni.io/vocdoni-api/list-organization-elections-by-status))
- [x] `POST /elections/filter/page/{page}` ([docs](https://developer.vocdoni.io/vocdoni-api/list-elections-filtered))

## Organizations
- [x] `GET /chain/organizations` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] organizationId: string;

and this new endpoint replaces all the following, marked deprecated:
  - [x] `GET /chain/organizations/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-organizations))
  - [x] `POST /chain/organizations/filter/page/{page}` ([docs](https://developer.vocdoni.io/vocdoni-api/list-organizations-filtered))

## Accounts
- [x] `GET /accounts` now accepts following query params
  - [x] page: number;
  - [x] limit: number;

and this new endpoint replaces all the following, marked deprecated:
  - [x] `GET /accounts/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-of-the-existing-accounts))

## Votes
- [x] `GET /votes` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] electionId: string;

and this new endpoint replaces all the following, marked deprecated:
  - [x] `GET /elections/:electionID/votes/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-election-votes))
  - [x] `GET /elections/:electionID/votes/count` ([docs](https://developer.vocdoni.io/vocdoni-api/count-election-votes)) since /votes now reports totalItems

## Transactions
- [x] `GET /chain/transactions` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] height: number;
  - [x] type: string;

and this new endpoint replaces all the following, marked deprecated:
  - [x] `GET /chain/transactions/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-transactions))
  - [x] `GET /chain/blocks/:height/transactions/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/transactions-in-a-block))

## Fees
- [x] `GET /chain/fees` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] reference: string;
  - [x] type: string;
  - [x] accountId: string;

and this new endpoint replaces all the following, marked deprecated:
  - [x] `GET /chain/fees/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-all-token-fees))
  - [x] `GET /chain/fees/reference/:reference/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-all-token-fees-by-reference))
  - [x] `GET /chain/fees/type/:type/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-all-token-fees-by-type))
  - [x] `GET /accounts/:accountID/fees/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-account-token-fees))
  - [x] `GET /accounts/:accountID/transfers/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-account-received-and-sent-token-transfers))

## Transfers
- [x] `GET /chain/transfers` now accepts following query params
  - [x] page: number;
  - [x] limit: number;
  - [x] accountId: string;
  - [x] accountIdFrom: string;
  - [x] accountIdTo: string;

and this new endpoint replaces the following, marked deprecated:
  - [x] `GET /accounts/:accountID/transfers/page/:page` ([docs](https://developer.vocdoni.io/vocdoni-api/list-account-received-and-sent-token-transfers))
  > WARNING: exceptionally among all the changes introduced, this endpoint broke backwards compatibility (since it wasn't being used anyway), the json returned changed, now it's a plain list of transfers instead of "received" and "sent".

## "Count" endpoints are now redudant

since now all paginated endpoints return a totalItems, the following endpoints become redundant and are marked as deprecated:

- [x] `GET /accounts/{organizationId}/elections/count`
- [x] `GET /accounts/{accountId}/transfers/count`
- [x] `GET /accounts/count`
- [x] `GET /chain/organizations/count`
- [x] `GET /chain/transactions/count`
- [x] `GET /elections/{electionId}/votes/count`

> Note: I've added every single call I've seen requiring a `:page` param (which now should be GET params). I've also set some as "maybe to be merged with" because seems like we have different calls for filtering for different values, and all these could be unified in the same call by simply specifying the indexed field in the URL as a GET param.

Task vocdoni/vocdoni-node#1318 is related since after having that, those new stored metadata fields could/should be filterable via pagination.

### Steps or subtasks
Trying to disclose all the major tasks, since maybe they could be done in different steps:
- [x] Return `total` field in currently filtered endpoint responses.
- [x] Change from POST to GET the filtered endpoints, passing all filters and pagination params via GET params.
- [ ] Add new indexed fields to search by, like also via title and description from vocdoni/vocdoni-node#1318 
- [x] Unify all endpoints. Since the difference between `/elections` and `/elections/filtered` now will be based on "if it does or does not receive params", all features should be unified into the main endpoint.

**Comment by mvdan** [comment]
SGTM, happy to review. I don't oppose new APIs or a v2 per se, but I'm also not super pumped about starting from scratch unless we really have to.

**Comment by marcvelmer** [comment]
Sorry for reopening this but how about something like:

```
 "pagination": {
   "total_records": 22,
   "current_page": 1,
   "total_pages": 3,
   "next_page": 2,
   "prev_page": null
 }
 ```
 
 I think this is much more powerful for integrating with different UIs and shouldn't be a problem for calculating those data in the backend.

**Comment by altergui** [comment]
> Sorry for reopening this but how about something like:
> 
> ```
>  "pagination": {
>    "total_records": 22,
>    "current_page": 1,
>    "total_pages": 3,
>    "next_page": 2,
>    "prev_page": null
>  }
> ```
> 
> I think this is much more powerful for integrating with different UIs and shouldn't be a problem for calculating those data in the backend.

LGTM and i agree it would be easy,
just a small nit: in your example the starting page is 1 and currently in the api we consider 0 to be the first page (so specifying param `page=0` or specifying no param is equivalent, also for backwards compatibility)
do we really want to switch to 1?
or keep everything in the api "0 indexed" and let the UI do +1 to everything?

**Comment by marcvelmer** [comment]
> > Sorry for reopening this but how about something like:
> > ```
> >  "pagination": {
> >    "total_records": 22,
> >    "current_page": 1,
> >    "total_pages": 3,
> >    "next_page": 2,
> >    "prev_page": null
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this is much more powerful for integrating with different UIs and shouldn't be a problem for calculating those data in the backend.
> 
> LGTM and i agree it would be easy, just a small nit: in your example the starting page is 1 and currently in the api we consider 0 to be the first page (so specifying param `page=0` or specifying no param is equivalent, also for backwards compatibility) do we really want to switch to 1? or keep everything in the api "0 indexed" and let the UI do +1 to everything?

I would keep the first page as 0, sure

**Comment by elboletaire** [comment]
For backwards compatibility it should remain as 0.

But please, for future (new) implementations, consider using 1... I think this is the very first time I've seen a pagination starting with page 0 tbh.

**Comment by marcvelmer** [comment]
![ph01](https://github.com/vocdoni/interoperability/assets/16820387/1b2c89e0-3504-405f-aa77-4d3bffbe806a)

**Comment by altergui** [comment]
so far,  here's my progress in https://github.com/vocdoni/vocdoni-node/pull/1341
```
    * api: add `pagination` field to endpoints:
      * GET /elections
      * GET /accounts
      * GET /chain/organizations
    
    * api: refactor filtered endpoints to unify pagination logic (and add `pagination` field):
      * GET /accounts/{organizationID}/elections/status/{status}/page/{page}
      * GET /accounts/{organizationID}/elections/page/{page}
      * GET /elections/page/{page}
      * POST /elections/filter/page/{page}
      * GET /chain/organizations/page/{page}
      * POST /chain/organizations/filter/page/{page}
      * GET /accounts/page/{page}
    also, marked all of these endpoints as deprecated on swagger docs
```

i.e. i implemented all of this

- [x] Return total field in currently filtered endpoint responses.
- [x] Change from POST to GET the filtered endpoints, passing all filters and pagination params via GET params.
- [x] Unify all endpoints. Since the difference between /elections and /elections/filtered now will be based on "if it does or does not receive params", all features should be unified into the main endpoint.
- [x] return a `pagination` struct like @marcvelmer suggested instead of simply `total`

but not yet for ALL endpoints mentioned, only the "Important ones" from the original post.

i also didn't yet "Add new indexed fields to search by, like also via title and description from https://github.com/vocdoni/vocdoni-node/issues/1318"

**Comment by altergui** [comment]
btw yesterday we agreed with @elboletaire to limit the scope of a first MVP: just refactor all the current "URL params" and "POST params", allowing them to be passed via "Query params".
and focus on extending this refactor (unifying behaviour) to all endpoints that currently accept `page` as URL param (listed by OP)

then on a second step (another PR), add NEW filters like `finalResults=true&manuallyEnded=true` and whatnot.

the only exception would be param `limit`, which is currently not supported by any endpoint, but would be part of the MVP since it's so fundamental to pagination (actually i already implemented it in the PR)

**Comment by altergui** [comment]
wishlist of paginated endpoints after this MVP

 * [ ] `GET /chain/blocks` (see https://github.com/vocdoni/interoperability/issues/33)
 * [ ] `GET /chain/validators`

**Comment by altergui** [comment]
wishlist of new filters (all of these names are tentative, exact param names TBD)
* /elections
  * startDateBefore
  * startDateAfter
  * endDateBefore
  * endDateAfter

* /accounts
  * accountId (substr)
  
* /chain/transactions
  * fromAccount
  * toAccount

**Comment by altergui** [comment]
i missed two current endpoints in my merged PR:

* /accounts/{accountId}/fees/page/{page}
* /accounts/{accountId}/transfers/page/{page}

the first one i'll simply mark is as deprecated in favor of `/chain/fees?accountId=`

the second one will turn into a new endpoint:
* /chain/transactions
  * page
  * limit
  * fromAccountId
  * toAccountId

**Comment by altergui** [comment]
> i missed two current endpoints in my merged PR:
> 
>     * /accounts/{accountId}/fees/page/{page}
> 
>     * /accounts/{accountId}/transfers/page/{page}
> 
> 
> the first one i'll simply mark is as deprecated in favor of `/chain/fees?accountId=`
> 
> the second one will turn into a new endpoint:
> 
>     * /chain/transfers
>       
>       * page
>       * limit
>       * fromAccountId
>       * toAccountId

done in https://github.com/vocdoni/vocdoni-node/pull/1359
