### ISSUE TITLE
Implement TX list by block height

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#190]
Actually the way to get the tx list on a block is to get every single tx using the `data.txs.length` of the block and looping every index `/chain/transactions/:height/:index`.

After talk with @altergui he said that a refactor will be done backend side to return a list of transactions by block height.

Explorer related issue https://github.com/vocdoni/explorer/issues/50

**Comment by selankon** [comment]
The method actually exists https://developer.vocdoni.io/vocdoni-api/transactions-in-a-block

But we need to get the total number of transactions on the block information

**Comment by altergui** [comment]
> But we still need to get the total number of transactions on the block information

addressed in https://github.com/vocdoni/vocdoni-node/pull/1329/commits/f16e92db3c653c629b55fdcf301bcbc039f91c1a

**Comment by selankon** [comment]
This need to be implemented on the SDK types and on to the explorer
