### ISSUE TITLE
Deploy new Explorer to LTS

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#193]
As Vocdoni we want to deploy the new explorer to  the LTS network.

- [x] Finish the pagination and filtering issues
- [x] Update the API
- [x] https://github.com/vocdoni/explorer/issues/65
- [x] Create the new SDK package
- [x] Deploy to STG
- [x] Review & Test
- [x] Merge Vochain changes
- [x] Deploy to LTS

Check:
- [ ] https://github.com/vocdoni/ui-scaffold/issues/740

**Comment by elboletaire** [comment]
Closing, since the main issue's been done. The links review tasks are open on each project that might require changes.
