### ISSUE TITLE
Standarize pagination endpoints

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#20]
standarize how it paginate the list pages, for example for elections you can use `v2/elections` or either` v2/elections/page/0`.

Instead, for transactions you can only use `v2/chain/transactions/page/0`. On a meeting we decided to use only `page/0` ones.

Methods where you can access to page 0 without the parameter `page0`

- [ ] `/elections` 
    - [ ] Developer portal
- [ ] `chain/organizations` 
    - [ ] Developer portal
- [ ] `accounts/{accountId}/elections` 
    - [ ] Developer portal
- [ ] `/accounts/:accountId/transfers/` // I didn't know any account with transfers so I can't check it 
    - [ ] Developer portal
- [ ] `/elections/:electionId/votes/`
    - [ ] Developer portal

**Comment by jordipainan** [comment]
Taking it
