### ISSUE TITLE
max census size

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#21]
The MaxCensusSize parameter is a new feature introduced in the blockchain that is used to limit the number of votes that can be registered for an election. This feature helps to prevent any potential overflow of the blockchain when the number of votes goes beyond the maximum limit.

In order to create an election, the creator is required to set the MaxCensusSize parameter to a proper value. Typically, this value should be equal to the size of the census. If the MaxCensusSize parameter is set to 0, an error will occur and the election cannot be created.

The MaxCensusSize parameter determines the maximum number of votes that can be registered by the blockchain. If the number of votes exceeds this limit, the vote transaction will fail.

Additionally, there is a global MaxCensusSize defined in the blockchain's Genesis. This is the maximum value that an election creation can allow. This value can be accessed through the /chain/info API endpoint.

- [x] SDK (needs upgrade on the protobuf models) 
- [ ] Documentation (it would be great to use the previous text to explain this parameter)

**Comment by selankon** [comment]
@p4u actually the `maxCenusSize` is not sent on `/chain/info`. 

```
curl https://api-dev.vocdoni.net/v2/chain/info -s | jq . 
```

Additionally, a part of the text should be added on the API reference and the other on the SDK JSDocs or on other side, because is related to the SDK election create process. I have to see how to handle all.

**Comment by selankon** [comment]
Also,

> The `MaxCensusSize` parameter determines the maximum number of votes that can be registered by the blockchain. 
          If the number of votes exceeds this limit, the vote transaction will fail.

What happen if there are vote overrides? Will break this rule?

**Comment by p4u** [comment]
> @p4u actually the `maxCenusSize` is not sent on `/chain/info`. 
> 
> ```
> curl https://api-dev.vocdoni.net/v2/chain/info -s | jq . 
> ```
> 
> Additionally, a part of the text should be added on the API reference and the other on the SDK JSDocs or on other side, because is related to the SDK election create process. I have to see how to handle all.

Its not yet deployed

**Comment by marcvelmer** [comment]
Added to the SDK in version `0.0.7`

**Comment by selankon** [comment]
I reopen the issue because I have to merge the docs of the `maxCenusSize` on the developer portal `/chain/info` endpoint. 

FTR, the sdk return this error when the blockchain census size is rebased.

```ts
throw new Error('Max census size for the election is greater than allowed size: ' + this.chainData.maxCensusSize)
```

**Comment by selankon** [comment]
@jpaulet  could be useful to add docs to this interface? For the `maxCensusSize` for example 

https://github.com/vocdoni/vocdoni-sdk/blob/main/src/types/election/election.ts#L23

**Comment by selankon** [comment]
Either @p4u shoud election info return the `maxCensusSize` somewhere?

**Comment by jpaulet** [comment]
> @jpaulet could be useful to add docs to this interface? For the `maxCensusSize` for example
> 
> https://github.com/vocdoni/vocdoni-sdk/blob/main/src/types/election/election.ts#L23

Yes, I think that could be interesting to explain in more detail, not only this one, all 3 interfaces: IVoteType, IElectionType & IElectionParameters if they don't exist.

**Comment by p4u** [comment]
> curl https://api-dev.vocdoni.net/v2/elections/c5d2460186f7d1e92e94ce4364ee7be44c6e70960ce9bccd9ba6020000000000 -s | jq .

Right! Added.

**Comment by selankon** [comment]
Added maxCensusSize to swagger election info response

https://github.com/vocdoni/developer-portal/pull/53
