### ISSUE TITLE
Implement block list endpoint

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#220]
This PR implements a block list endpoint on the API: https://github.com/vocdoni/vocdoni-node/pull/1329

This have to be implemented on:

- [ ] Type and export the interface on the SDK and implement the endpoint on the `ChainAPI` 
- [ ] The block details interface have to be updated on the SDK. At least a new attribute is added (`txCount`) and others may be dissappeared (`txs`)
- [ ] Implement the method on the Extended SDK
- [ ] Implement the blocklist on the explorer

**Comment by altergui** [comment]
here's what i have so far:

* GET /chain/elections
  * page
  * limit
  * chainId
  * hash
  * proposerAddress

chainId and proposerAddress matches exactly, 
hash matches partially (substring)

**Comment by altergui** [comment]
in the reply, not all blocks listed will have all their fields filled in, since back at the time we only indexed height and timestamp. so the first N blocks will only return height and timestamp, i.e. no hash, chainId nor proposerAddress. also they won't be included in results when using any of those filters, of course

**Comment by altergui** [comment]
since that PR will take longer, i cherry-picked and adapted the relevant code to work without the indexer, to not block this interop issue longer
https://github.com/vocdoni/vocdoni-node/pull/1369

**Comment by altergui** [comment]
> here's what i have so far:
> 
>     * GET /chain/blocks
>       
>       * page
>       * limit
>       * chainId
>       * hash
>       * proposerAddress
> 
> 
> chainId and proposerAddress match exactly, hash matches partially (substring)

@marcvelmer this is what i implemented and is merged on backend (the filters don't actually filter yet, but for interop it's irrelevant since the format of the params and the returned reply won't change when that's finished)

https://developer.vocdoni.io/vocdoni-api/list-all-blocks
