### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#223]
As an admin, I want to view a detailed pricing page so that I can understand the costs associated with different subscription plans and features.

**Tasks:**
- [x] Pricing Page UI:
- A detailed page displaying all available subscription plans.
- Features comparison table for each subscription tier.
- "Subscribe" or "Upgrade" buttons for each plan.
- FAQs or additional information regarding pricing and plans.

**Acceptance Criteria:**
- Admin can view all available subscription plans and their details.
- Admin can easily compare different plans and their features.
- Admin can select a plan and initiate an upgrade or subscription change.
- Appropriate success or error messages are displayed based on the outcome.
- The current subscription plan of the admin is shown.
- If the org has already a plan, only show the "bigger" plans: (i.e: if the plans are 1,2,3 & 4 and the current org is in the plan 2 ("Pro"), only show the 3 & 4 plans to upgrade). 

**Visuals:**
![Pricing](https://github.com/user-attachments/assets/62ffd1ae-c9ff-4e9b-8e89-734c98308a61)

_____

![image](https://github.com/user-attachments/assets/f11c4b25-3b1e-4f9b-9747-6a773f336427)

**Comment by jordipainan** [comment]
1. Free

- Up to 10 voters
- What are the essential features ?
- 2 processes a year (add limitations like duration, features etc.)
- No support

2. Essential

- What are the core voting features?
- 1 admin (it is always 1 org, we do not have the option of multiple orgs)
- 2 yearly voting processes
- What includes the basic reporting and analytics ?
- Ticket support
- Delete GDPR compliance (it is always GDPR compliant)

3. Premium

- Up to 3 admins
- 5 yearly voting processes
- What includes the reporting and analitics ?
- Ticket and priority email support
- Delete GDPR

4. Custom

- All features
- Unlimited admins
- Suborganizations
- Unlimited voting processes
- Delete advanced security features (all plans are equally secure)
- What is a dedicated account manager
- Add SLA ?
- Ticket, priority email support, phone/chat realtime support.

Add in all UP to X  voters (mention discount x voter on each plan depending on the size if required)
