### ISSUE TITLE
Pricing/Subscription Modal

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#224]
As an admin, I want to receive a prompt when I try to access a feature that is not available in my current subscription plan, so that I can upgrade my plan. 

When I attempt to access a feature that is either not included in my current plan or exceeds the plan's limits, I should be prompted with a modal offering me the option to upgrade to a higher tier. This modal should inform me about better plans, encourage me to upgrade, and allow me to proceed with the upgrade if needed.

**Tasks:**
- [x] Permissions and Upgrade Modal UI:
- A modal that pops up when an admin tries to access a restricted feature.
- Clear messaging indicating why access is denied (e.g., "This feature is not available in your current plan.").
- Options to upgrade the subscription plan.
- A link to the pricing page for more information.
- The modal should be customizable (be able to display the requested feature) and must be prepared to be displayed at any point within the SaaS platform.
- [x] Integration with Feature Access Management:
- Frontend checks to determine feature access based on the current subscription plan.
- Integration with the backend API to fetch the admin's current plan and feature availability.

**Acceptance Criteria:**
- Admin receives a modal prompt when attempting to access a restricted feature.
- The modal clearly explains the lack of access and provides options to upgrade or learn more.
- Admin can successfully upgrade their plan directly from the modal.
- Appropriate success or error messages are displayed based on the outcome.

**Visuals:**
![Pricing(1)](https://github.com/user-attachments/assets/ed4307cc-664e-445c-bec1-f48b1744f718)

**Comment by elboletaire** [comment]
Can be closed now
