### ISSUE TITLE
New ProofArbo protobuf definition to support custom weight on weighted voting 

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/interoperability#25]
The definition of the ProofArbo protobuf has been updated to support to voters using a custom weight when voting.

To allow this behaviour, the old `ProofArbo.value` has been renamed to `ProofArbo.leafWeight`, which represents the weight assigned to the voter when the census was created. A new attribute has also been included called `ProofArbo.votingWeight`, which represents the weight desired by the voter.

The `votingWeight` must be less than or equal to the `leafWeight` (aka `factoryWeight`).

Some considerations:
- The API requires a valid value for `factoryWeight` to perform a vote, `votingWeight` is optional.
- By default, the API will use the `factoryWeight` as `votingWeight` if no value is provided.

- [ ] add to documentation
- [ ] update to SDK

**Comment by lucasmenendez** [comment]
In an attempt to clarify these terms, i porpoise replace them with:
 - **`censusWeight`**: The weight used by the election creator to register the voter into the census.
 - **`userWeight`**: The weight desired by the voter to perform a vote. It must be less than or equal to `censusWeight`.

To avoid misunderstandings, these changes will be included across `vocodni-node` source code, but also in the `.proto` definitions. Then, this terminology needs to be used also in the `vocdoni-sdk` as well.

What do you think? @marcvelmer @jpaulet @jordipainan @p4u

**Comment by jpaulet** [comment]
What if we use something more descriptive, like:

- _attributedUserWeight_ or (_attributedWeight_)
- _usedUserWeight_ or (_usedWeight_)

**Comment by jpaulet** [comment]
We go with Marc proposal: availableWeight + voteWeight.

**Comment by lucasmenendez** [comment]
Draft PR's opened:
- https://github.com/vocdoni/vocdoni-node/pull/897
- https://github.com/vocdoni/dvote-protobuf/pull/61

We will merge both PR's when the SDK changes are ready (in a new SDK release)
