### ISSUE TITLE
api: GET /elections/<electionID>/scrutiny

### ISSUE THREAD

**Issue by jordipainan** [vocdoni/interoperability#3]
This endpoint returns a given election consensus results and useful information about the results.

- Request:
```http
GET /elections/<electionID>/scrutiny
```
- Response:
```json
{
  "abiEncoded": "0x376461323730326633376664343865356231623961353731356533353039623600000000cccccaaabbb...",
  "censusRoot": "0x3764613237303266333766643438653562316239613537313565333530396236",
  "electionId": "0x6461323730326633376664343865356231623961353731356533353039623600",
  "organizationId": "0xcc79157eb46f5624204f47ab42b3906caa40eab737"
  "results": [
    [1, 2, 3],
    [4, 5, 6]
  ],
  "sourceContractAddress": "0xcc79157eb46f5624204f47ab42b3906caa40eab7"
}
```

This method can be used by anyone, but it is also used by Chainlink for fetching Vochain results and store it to the Results contract on an EVM network. 

For discovering more about the on-chain results, please refer to [chainlink-tally repository](https://github.com/vocdoni/chainlink-tally#chainlink-tally).
The most important part of the on-chain results is that any user can call the setResult(processId, chainName) to trigger a result upload from the Vochain to an EVM network. 

Is it an action that we want to add to the SDK? Another option is to create a simple frontend that allows to trigger this action. I've created a Golang CLI tool that allows to do so.
It is also another option to automate the process by creating a software artifact that listens the Vochain for new results and sends the tx to Ethereum automatically. Notice that this means that we are going to pay for the gas, ETH + LINK.

**Comment by selankon** [comment]
It should return accountId instead of a organizationId?

**Comment by selankon** [comment]
The developer portal document this endpoint here:

https://github.com/vocdoni/developer-portal/pull/33

**Comment by selankon** [comment]
Is pending to talk about how to integrate this on the SDK
