### ISSUE TITLE
[Bug] - cspStep returns 405 error

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#32]
When calling to `vocdoniClient.cspStep()`  (from the CSP) a request is sent to `/auth/elections/info` that returns a `405 Error`. 
_For more info, talk with Aleix (nigeon)_

**Comment by p4u** [comment]
Hey @nigeon, is the info endpoint implemented in your handler?

**Comment by nigeon** [comment]
Ah, of course. Yeah, The info endpoint was there, BUT I had configured http://localhost:5000/ as csp URL, and it must be http://localhost:5000/v1/
