### ISSUE TITLE
Deprecate the usage of publicKeys on census

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#34]

**Comment by marcvelmer** [comment]
Done in https://github.com/vocdoni/vocdoni-sdk/pull/138

**Comment by marcvelmer** [comment]
@lucasmenendez @p4u Can we close the issue? In the SDK it's already done. AFAIK also in the backend, right?

**Comment by p4u** [comment]
Let's finish first the backend part, then we can close.

**Comment by lucasmenendez** [comment]
Its ready to review here: https://github.com/vocdoni/vocdoni-node/pull/882
