### ISSUE TITLE
Add endpoint to get transactions references of a specific block

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#57]
On the explorer you can access to a block detail and see the transactions registered on it. We need and endpoint to replace this, proposed by @p4u:

`/chain/transactions/reference/height/{height}`

Should return a list of transactions reference like:

```
[
   {
     "transactionNumber": 1,
     "transactionHash": "8bb5f1c52ab1d1f1cdedb85d3469af91e55a7971e777db50f896ed18a8136028",
     "blockHeight": 24,
     "transactionIndex": 0,
     "transactionType": "setAccount"
   }
]
```

- [x] Vocdoni node implementation
- [x] SDK
- [x] Developer portal

**Comment by selankon** [comment]
This is related to this issue: https://github.com/vocdoni/explorer-ui/issues/123 

We detected that the `getTxListForBlock` method from the old rpc doesn't work properly

**Comment by jordipainan** [comment]
How about this response? @selankon 

```json
{
    "blockNumber": 123456,
    "transactionNumber": 3,
    "transactions": [
        {
            "type": "transfer",
            "index": 0,
            "hash": "0x0123456789abcdef"
        },
        {
            "type": "approve",
            "index": 1,
            "hash": "0x0123456789abcdef"
        },
        {
            "type": "transfer",
            "index": 2,
            "hash": "0x0123456789abcdef"
        }
    ]
}
```

**Comment by selankon** [comment]
Hi @jordipainan . 

This seem enough. I miss on the tx reference the transaction height (or transactionNumber). Actually on the transaction card it appear, and could be interesting. Otherwise we can show the index instead of the height.

Also, `transactionNumber` could be `transactionCount` instead (more descriptive?)

**Comment by selankon** [comment]
This is implemented on vocdoni node but seems to have a bug, what is this first transaction on the list @jordipainan ?:

```bash
curl https://api-dev.vocdoni.net/v2/chain/transactions/reference/height/1500 -s | jq
{
  "blockNumber": 1500,
  "transactionCount": 1,
  "transactions": [
    {
      "type": "",
      "height": 0,
      "index": 0,
      "hash": ""
    },
    {
      "type": "vote",
      "height": 24,
      "index": 0,
      "hash": "924c4c9bdceab4055576994cf7312b7269c0715229a9660a6f4c9559256892c6"
    }
  ]
}
```

**Comment by selankon** [comment]
And another thing to take on account is that this list is not paginated and should be imho

**Comment by jordipainan** [comment]
> 

yup, the first one is totally incorrect, will look at the db queries and fix it

**Comment by jordipainan** [comment]
> And another thing is to use the same names used on other endpoints to show transactions references (see the issue description to show which names are used), in order to reuse the objects. For example, when getting transactions list, the references are:
> 
> ```shell
> curl https://api-dev.vocdoni.net/v2/chain/transactions/page/0 -s | jq    
> {
>   "transactions": [
>     {
>       "transactionNumber": 28,
>       "transactionHash": "60bc4e4b7fb229e5b5258e590b7abf2743d1a2e6ee70086bf05a8ea9029227ea",
>       "blockHeight": 3122,
>       "transactionIndex": 0,
>       "transactionType": "newProcess"
>     },
> ```
> 
> Either, I think that for me the endpoint is not clear, because you are consulting by block height, but the path namespace is transactions. For example `chain/blocks/height/1500/transactions` is clearer to me, IMHO.
> 
> Also is a bit confusing because this endpoint is `chain/transactions/reference/height/1500` "get transactions by block height" and there are another that is `chain/transactions/reference/index/7` that is "get transaction reference by transaction index"

oki, going to change to the names referenced in the comment.
I do no have an strong opinion on the endpoint paths but I do see that is under transactions because even if you are asking for a specific block you are still asking for transaction info.
Despite this I agree that `chain/blocks/height/1500/transactions` is an option, and you have an strong opinion for changing it I think we are all open.

**Comment by jordipainan** [comment]
> And another thing to take on account is that this list is not paginated and should be imho. See this one with 25 transactions is breaking
> 
> ```shell
> curl https://api-dev.vocdoni.net/v2/chain/transactions/reference/height/52200  -s | jq
> ```

agree, adding pagination

**Comment by jordipainan** [comment]
> And another thing to take on account is that this list is not paginated and should be imho. See this one with 25 transactions is breaking
> 
> ```shell
> curl https://api-dev.vocdoni.net/v2/chain/transactions/reference/height/52200  -s | jq
> ```

I am not sure about adding pagination here, this is an expensive query, because we are asking to the state, and the transactions of the block are all returned. So this would mean do the same work N pages

**Comment by selankon** [comment]
FTR, with the old RPC we got this paginated: https://github.com/vocdoni/explorer-ui/blob/54a29fe745d2112b78bba16e5e52e1ac6cc7f975/hooks/use-transactions.tsx#L9

```ts
 return fetchMethod(pool, {
          method: 'getTxListForBlock',
          params: {
            height: blockHeight,
            listSize: listSize,
            fromId: fromId,
          },
        });
```

**Comment by jordipainan** [comment]
After a short talk, adding pagination :)

**Comment by jordipainan** [comment]
https://github.com/vocdoni/vocdoni-node/pull/991

**Comment by selankon** [comment]
Example of the result

```
curl /chain/blocks/{height}/transactions/page/{page} -s | jq


{
  "transactions": [
    {
      "transactionNumber": 28,
      "transactionHash": "60bc4e4b7fb229e5b5258e590b7abf2743d1a2e6ee70086bf05a8ea9029227ea",
      "blockHeight": 3122,
      "transactionIndex": 0,
      "transactionType": "newProcess"
    },
  ]
}
```

**Comment by selankon** [comment]
Documented https://github.com/vocdoni/developer-portal/pull/89
