### ISSUE TITLE
Truncate the decimals when voting with token weight

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#60]
Right now, when voting with token weight, the UI shows the total nº of decimals of the corresponding token in the "voting power" results, without truncating them, ex: 180000000000000000 instead of 18. It has different implications:

- [x] Manage it from the SDK side and serve it already truncated. 
- [x] vocdoni/ui-components#54

**Comment by elboletaire** [comment]
Done in chakra-components and already available in ui-scaffold (in develop branch, waiting to be deployed).
