### ISSUE TITLE
 Update API endpoints with extra documentation and introduce metadata information

### ISSUE THREAD

**Issue by emmdim** [vocdoni/interoperability#65]
The idea to follow up with the automatic swagger generation is to move some of the docs on the developer portal swagger to the comments on the vocdoni node code and test if everything works well. 

Objectives:

- Check if is possible to move part of the docs on external files in order to don't have the swagger metadata on the docs
- Check if the object shcemas generation works well
- See if the added documentation doesn't break code readability. 

As we agreed I am going to migrate the docs for some endpoints first to see the results.

Related to https://github.com/vocdoni/interoperability/issues/62

**Comment by selankon** [comment]
I am looking to the swaggo documentation and I found [this example](https://github.com/swaggo/swag/tree/master/example/markdown) where they use markdown files to store additional descriptions for tags, and api description or endpoints descriptions. 

So it support the description on separated .md files, but apparently only the description.

**Comment by selankon** [comment]
After little of research I created this PR which add better docs on the `/chain/transactions/reference/{hash}` endpoint and the swagger metadata. Use the following command to generate the swagger:

```bash
go run github.com/swaggo/swag/cmd/swag init --parseDependency --parseDepth 1 --parseInternal --md docs/descriptions -g api.go
```

- The swagger metadata can be placed anywhere of the entry file
- De API description and endpoint description is placed on outer markdown files
- The most important difference is the example and schema generated docs, which mean that the return objects could be documented as well to improve the docs. For example, this image is for the actual developer page 

![image](https://github.com/vocdoni/interoperability/assets/16777076/bc81c073-5738-4cca-a823-b8b4e4e55166)

![image](https://github.com/vocdoni/interoperability/assets/16777076/019fd990-5386-4716-8fe0-c44871bcb25f)

And the following is with the generated code from the added docs:

![image](https://github.com/vocdoni/interoperability/assets/16777076/b66c7d53-2dd9-44c6-b36b-ea0235f57c68)

![image](https://github.com/vocdoni/interoperability/assets/16777076/c9697cc8-efb8-4e1a-950a-b2f18fce4f17)

We can research further to try to improve the response object schemas.

**Comment by emmdim** [comment]
@chilcano  The next task is:
https://github.com/vocdoni/interoperability/issues/65
