### ISSUE TITLE
Add symbols to the census3 token response list call

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#74]
When calling `/api/token` for obtaining a list of tokens, the following information is returned for each token result:

~~~json
{
  "id": "0xa117000000f279D81A1D3cc75430fAA017FA5A2e",
  "type": "erc20",
  "startBlock": 11060110,
  "name": "Aragon Network Token"
}
~~~

Having the symbols here (i.e. `"symbol": "ANT"`) would allow us to create lists that can be filtered not only by name, but also by their symbol.

**Comment by marcvelmer** [comment]
SDK Done: https://github.com/vocdoni/vocdoni-sdk/pull/202
