### ISSUE TITLE
Add an `ActualEndBlock` field and make it available in the elections API

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#76]
We only have an EndBlock field right now, and that does not give correct information when we end an election before such end date (because it's not updated).

Add a new `ActualEndBlock` field and fill it with the block number at which the election was actually ended.

Issue triggered by https://github.com/vocdoni/ui-scaffold/issues/132

**Comment by jordipainan** [comment]
Why not adding this into the state seamlessly using the IST and modify the endBlock when the election is finished ?
It is breaking, but IMO it is more correct and consistent.
This way you do not end-up having 2 attributes giving the same information in terms of utility of this information.

**Comment by elboletaire** [comment]
Wouldn't that be changing the end date set by the user to a different one (aka losing the initial information)?

**Comment by jpaulet** [comment]
@p4u any feedback here?

**Comment by jordipainan** [comment]
> Wouldn't that be changing the end date set by the user to a different one (aka losing the initial information)?

yes, but do we want to keep it? if the election ends why would you like to have both? In the end the results will be "applied" based on the latest endDate.

It is not a big deal to add in on the scrutinizer but I think this should be part of the state ... so adding there 2 "endDates" IMO is overcomplicate things

**Comment by elboletaire** [comment]
Call me data hoarder, but I think the more data the better.

Also, it could be used as a means to know if a process has been manually ended (endBlock != actualEndBlock).

**Comment by p4u** [comment]
**Proposal**

The indexer should update the `endDate` field when the election is ended by transaction. 

Add `maxVotingTimeConsumed` to true/false (to know if the election as closed manually)

@elboletaire @marcvelmer  what do you think?

**Comment by elboletaire** [comment]
I think that's a terrible name for the var 😂 other than that.. I really don't have a good reason to store two different values, other than having more data "in case we wanna show it"... after all, the problem is solved in either case.

**Comment by p4u** [comment]
> I think that's a terrible name for the var joy other than that.. I really don't have a good reason to store two different values, other than having more data "in case we wanna show it"... after all, the problem is solved in either case.

What would you name it?

**Comment by elboletaire** [comment]
It's not like it's a bad name, but it took me a while to understand it as you described (using it to know if it has been paused or not). Also, if I decide to stop the event in the exact same block (very weird and unlikely), it would not be indicating that it ended manually, right?

So, why not add a "specific" field for it? Something like "manuallyStopped", only filled when running the action manually , wouldn't be giving the same information?

**Comment by p4u** [comment]
Ok, I'm returning manuallyStopped. I could also return the original "block count", or original "end date". But that's probably messing rather than adding value. What do you think?

**Comment by elboletaire** [comment]
So you propose to update the endBlock when running the action, but at the same time have an extra field for the original block it was gonna be closed? That makes sense for me (since I said before "the more data the better"), and also simplifies implementations logic, since doing it the way you propose, end-developers won't need to make a condition to show one or the other.

SGTM

**Comment by p4u** [comment]
Addressed here https://github.com/vocdoni/vocdoni-node/pull/1053

```json
  "manuallyStopped": true,
  "endBlock": 21872,
```

@marcvelmer there is a new field in the election summary API data model. It is returned on `/elections/:id` and `/elections/page/:page`

**Comment by elboletaire** [comment]
I think we can close this now.
