### ISSUE TITLE
CORS errors in UI-Scaffold when calling API-STG

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#80]
From time to time, the API returns null for some requests, but it's random and in all cases tends to happen after successful requests have been made.

The only way I've seen the issue is by staying in scaffold election pages for quite long, like this one for example: https://vocdoni.github.io/ui-scaffold/stg/#/processes/0xc5d2460186f74a081070e9d555b5d19629a6bcc8b77f4ae6d39c02000000001b

The scaffold does have a request loop every 30 seconds to check stuff like the process details and if you're in the census. Some of these request may fail randomly, causing the app to show an error (which disappears after 30s, since a new request is made and that's usually successful):

![imatge](https://github.com/vocdoni/interoperability/assets/153305/82220036-1829-4432-bbe6-05f8dd8d52fa)

All these failures have in common that they do not return a response at all. Both the status code and the body are empty:

![imatge](https://github.com/vocdoni/interoperability/assets/153305/add62afc-0923-445a-9452-a38fac6fd5f3)

BTW I've only been able to reproduce it using the stg API, but only because I don't tend to work using the dev API.

**Comment by elboletaire** [comment]
If everything is the same speaking of backend, infrastructure, etc... then yes, it might be happening with api-dev too.

**Comment by mathewmeconry** [comment]
Hey @elboletaire 
I tried reproducing it for a few days and left the tab open. No luck. Do you still experience this issue or have you figured out another way to reproduce it?

**Comment by elboletaire** [comment]
Actually more than ever...

![imatge](https://github.com/vocdoni/interoperability/assets/153305/5e3099c7-855f-4ab3-a096-62d74aa59ce3)


I did changes to the UI-scaffold and the errors are not shown anymore on screen, but if you check the calls, many of them are returning CORS errors due to being empty responses.

**Comment by elboletaire** [comment]
After thoroughfully trying this with multiple browsers, seems to be an issue with firefox (I've tried disabling all addons, and I still had the issue, which confused me a lot).

I've not been able to reproduce it in other browsers after having the tab opened for quite long, so I'd say it's (my) firefox's fault.
