### ISSUE TITLE
[ SDK ] - Add the "sign" multistep in the SDK

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#86]
When the user needs to sign multiple TX, the SDK should support the multi-step and be able to guide the UI trough the process in order to let the user knows the nexts steps. 

- [ ] Create account
- [x] Create election
- [x] Vote without anonymous
- [x] Vote with anonymous
- [ ] Testing
- [ ] UI-Integration Flows in the modals

**Comment by marcvelmer** [comment]
Create election: https://github.com/vocdoni/vocdoni-sdk/pull/272
