### ISSUE TITLE
Finish the token/faucet integration in the UI-scaffold

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#88]
- [x] Check balance
- [x] Calculate proposal cost
- [x] Add "faucet" button
- [x] Add election cost info (detailed info)
- [x] Test the flow in testing network

**Comment by elboletaire** [comment]
For a proper integration we need faucets in every deployed network (at least dev and stg as of now). We only have one for stg deployed, how do we proceed for the api-dev deployments?

**Comment by nigeon** [comment]
@elboletaire  I'll provide the url for the dev faucet backend

**Comment by elboletaire** [comment]
As we already spoke, there won't be a faucet under the api-dev environment. I'm merging it right now.

**Comment by nigeon** [comment]
@jpaulet please close if done :)

**Comment by elboletaire** [comment]
We still need to publish it to app.vocdoni.io. I'll try to do it today ASAP, but I'm still waiting for a PR with changes on this matter to be done. I'll keep you posted.

**Comment by jpaulet** [comment]
> @jpaulet please close if done :)

After testing it.
