### ISSUE TITLE
API: ensure return objects containing lists

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#9]
Normally when we want to return a list of objects on a call the expected output is an object containing a list, ex:

```bash
curl https://api-dev.vocdoni.net/v2/chain/organizations/page/0 -s | jq
{
  "organizations": [
    {
      "organizationID": "d8f083a4db86a9f9b7b8a29dd15ab680a13123c7",
      "electionCount": 1
    },
//...
```

Meanwhile, there are calls that return a list of objects instead, for example:

```bash
curl https://api-dev.vocdoni.net/v2/chain/transactions/page/0 -s | jq

[
  {
    "transactionNumber": 908,
    "transactionHash": "bd9e2a8eb3d55b93d9adadecdf1e4270d704cf34e0c12497d21219624f746e71",
    "blockHeight": 15788,
    "transactionIndex": 0,
    "transactionType": "newProcess"
  },
//... 
```

List of endpoints that have to be fixed:

- [x] GET  `chain/transactions/page/0 `
- [x] GET `elections/`
- [x] GET `elections/{electionId}/votes`

After fix it:

- [x] Update docs
- [x] Update sdk

**Comment by lucasmenendez** [comment]
I am working on this issue [here](https://github.com/vocdoni/vocdoni-node/tree/bug/wrap_api_lists_into_objects). 

The example provided (`/chain/organizations/page/{pageNumber}`) returns an empty object, by omitting the `"organizations"` key when no results are found. I have tried to replicate this behaviour without creating new structs that only wrap these results.

**Comment by lucasmenendez** [comment]
Backend fixed and merged.

**Comment by selankon** [comment]
SDK implementation. 

For `chain/transactions/page/0`:

https://github.com/vocdoni/vocdoni-sdk/pull/102

For `elections/` list and `elections/{electionId}/votes`

https://github.com/vocdoni/vocdoni-sdk/pull/103

**Comment by selankon** [comment]
Updated docs on:

https://github.com/vocdoni/developer-portal/pull/40
